# Generated by Django 5.2.8 on 2025-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='kapak',
            field=models.ImageField(blank=True, null=True, upload_to='kapaklar/'),
        ),
    ]
